name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-project:
          - fizzbuzz
          - roman_converter
    steps:
      - uses: actions/checkout@v2
      - name: Run unittest
        working-directory: ${{matrix.target-project}}
        run: |
          python3 -m unittest discover -s tests/ -v
